### ISSUE TITLE
Create and Configure GitHub Repository

### ISSUE THREAD

**Issue by Nicmanthecodeman** [Nicmanthecodeman/CMPG323-Overview-25102737#1]
# User Story

> As a **student**, 
> I want to **create and configure a GitHub Repository**, 
> so that I can **plan, manage and track my progress throughout the semester more effectively**.

## Tasks (to be broken down further)

- [x] Create a repository named ‘CMPG 323 Overview - 25102737’ `Priority: 1`
- [x] Create the following Milestones: `Priority: 2`
    - [x] Project 1 Submission: Deadline – 18 August
    - [x] Project 2 Submission: Deadline – 8 September
    - [x] Project 3 Submission: Deadline – 29 September
    - [x] Project 4 Submission: Deadline – 20 October
    - [x] Project 5 Submission: Deadline – 3 November
    - [x] Exam (POE) Submission: Deadline – 18 November
- [x] Create the following Labels: `Priority: 2`
    - [x] Class
    - [x] Project
    - [x] Training
    - [x] \<any other labels you might find relevant>
