### ISSUE TITLE
Add a ReadME.md file to the repository

### ISSUE THREAD

**Issue by Nicmanthecodeman** [Nicmanthecodeman/CMPG323-Overview-25102737#2]
# User Story

> As a **student**,
> I want to **add a ReadME.md file to the repository**,
> so that **I can provide an updated overview and context for my semester projects (including epics, features, setup, etc.) for my Portfolio of Evidence (PoE)**.

## Tasks (to be broken down further)

- [x] In the ReadME.md, address which repositories will be created and used for each project `Priority: 1`
- [x] In the ReadME.md, provide a diagram explaining project and repository context and how they are integrated `Priority: 3`
- [x] In the ReadME.md, explain the branching strategy to be used within each project `Priority: 3`
- [x] In the ReadME.md, explain the use of a .gitignore file within each project `Priority: 3`
- [x] In the ReadME.md, explain the storage of credentials and sensitive information `Priority: 3`
