### ISSUE TITLE
Create and configure GitHub project

### ISSUE THREAD

**Issue by Nicmanthecodeman** [Nicmanthecodeman/CMPG323-Overview-25102737#3]
# User Story

> As a **student**,
> I want to **create and configure a GitHub Project**,
> so that I can **view and manage an overview of all the repositories (and projects). This includes issues, pull requests and statuses**.

## Tasks (to be broken down further)

- [x] Create a GitHub Kanban project `Priority: 1`
- [x] Link the GitHub repository to the project `Priority: 2`
- [x] Ensure that the project is named appropriately `Priority: 3`
- [x] Ensure that the project has a description adequately describing the project `Priority: 3`
- [x] Add the following columns: `Priority: 2`
    - [x] Linked Assessment (field type = text)
    - [x] Due Date (field type = date)
    - [x] Sprint (field type = single select; add all 8 of the sprints as options with sprint start and end date)
    - [x] Effort (in Hours) (field type = number)
