### ISSUE TITLE
Create and populate project views

### ISSUE THREAD

**Issue by Nicmanthecodeman** [Nicmanthecodeman/CMPG323-Overview-25102737#4]
# User Story

> As a **student**,
> I want to **create and populate project views**,
> so that I can **organize all the user stories, bugs, hotfixes or other related issues into views that showcases all the possible angles of the projects I am working in.**

## Tasks (to be broken down further)

- [x] Create a table view within the project named ‘Tabular View’ `Priority: 2`
    - [x] Add Milestone, Label, Linked Pull Request and Repository as fields to the view
    - [x] Hide the Assignees field
- [x] Create a board view within the project, named ‘Status View’ `Priority: 2`
    - [x] Group by Status
- [x] Create a board view within the project, named ‘Sprint View’ `Priority: 2`
    - [x] Group by Sprint
- [x] Create a table view within the project, named ‘Linked Assessment View’ `Priority: 3`
    - [x] Group by Linked Assessment
- [x] Create an additional customized view that provides you with additional insight into your semester progress
- [x] Populate the ‘Tabular View board’ with the following as tasks: `Priority: 1`
    - [x] All CMPG 323 classes
    - [x] All CMPG 323 training time required to upskill and complete projects
    - [x]  All estimated tasks required to complete all CMPG 323 projects
    - [x] All CMPG 323 project submissions (with deadlines attached to milestones)
    - [x] All tasks associated to completing the CMPG 323 Portfolio of Evidence (POE)
