### ISSUE TITLE
Create and configure project charts

### ISSUE THREAD

**Issue by Nicmanthecodeman** [Nicmanthecodeman/CMPG323-Overview-25102737#5]
# User Story

> As a **student**,
> I want to **create and configure project charts**,
> so that I can **see the bigger picture quickly of the status of the various projects in report format**

## Tasks (to be broken down further)

- [x] Add the following charts to the project:
    - [x] Number of Items by Label
    - [x] Number of Items by Status
    - [x]  Number of Items by Sprint
    - [x]  Burndown Chart
